{% set version = "v2.0.0" %}

package:
  name: metsim
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/metsim/metsim-{{ version }}.tar.gz
  sha256: 59f515efff5d4f1f5747d667c28e68baaffbd51389878841f24a5385b2c50ad7

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - ms = metsim.cli.ms:main

requirements:
  build:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - dask
    - netcdf4>=1.2.5
    - numba
    - numpy>=1.11.2
    - pandas
    - scipy>-0.18.1
    - toolz
    - xarray=0.10.9

test:
  imports:
    - metsim
    - metsim.methods
    - metsim.cli
  commands:
    - ms --help

about:
  home: https://github.com/UW-Hydro/MetSim
  license: GPL-3.0
  license_family: GPL3
  # TODO: remove license_file after https://github.com/UW-Hydro/MetSim/pull/138
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'Meteorology Simulator for Python'

  description: |
    MetSim is a meteorological simulator and forcing disaggregator for
    hydrologic modeling and climate applications. Metsim is based on MtClim and
    the preprocessor from version 4 of the VIC hydrologic model.
  doc_url: http://metsim.readthedocs.io/
  dev_url: https://github.com/UW-Hydro/MetSim

extra:
  recipe-maintainers:
    - jhamman
    - arbennett
    - bartnijssen
